SchimbValutar/UI.MVC/Controllers/CardController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Domain_Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UI.MVC.Data;

namespace UI.MVC.Controllers
{
    public class CardController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CardController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Card
        public async Task<IActionResult> Index()
        {
            return View(await _context.Card.ToListAsync());
        }

        // GET: Card/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card.SingleOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Card/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Card/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClientId,CursValutarStabilit,DataTranzactie,DenumireCard,NumarBonFiscal,NumarCard,NumarChitantaSchimbValutar,SerieChitantaSchimbValutar,SumaTranzactionata,ValoareLei,Valuta")] Card card)
        {
            if (ModelState.IsValid)
            {
                card.Id = Guid.NewGuid().ToString();
                _context.Add(card);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(card);
        }

        // GET: Card/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card.SingleOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }
            return View(card);
        }

        // POST: Card/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,ClientId,CursValutarStabilit,DataTranzactie,DenumireCard,NumarBonFiscal,NumarCard,NumarChitantaSchimbValutar,SerieChitantaSchimbValutar,SumaTranzactionata,ValoareLei,Valuta")] Card card)
        {
            if (id != card.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(card);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardExists(card.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(card);
        }

        // GET: Card/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card.SingleOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Card/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var card = await _context.Card.SingleOrDefaultAsync(m => m.Id == id);
            _context.Card.Remove(card);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CardExists(string id)
        {
            return _context.Card.Any(e => e.Id == id);
        }
    }
}

SchimbValutar/UI.MVC/Controllers/CursController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Domain_Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UI.MVC.Data;

namespace UI.MVC.Controllers
{
    public class CursController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CursController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Curs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Curs.ToListAsync());
        }

        // GET: Curs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curs = await _context.Curs.SingleOrDefaultAsync(m => m.Id == id);
            if (curs == null)
            {
                return NotFound();
            }

            return View(curs);
        }

        // GET: Curs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Curs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AcronimValuta,ActualizareValuta,CasierId,CursCumparare,CursOficialBnr,CursVanzare,DataCurs,DenumireValuta,Multiplu,NumarCurentValuta,NumarLista,ParitateEuro,PozitieValuta,SoldCurentValuta,TipValuta")] Curs curs)
        {
            if (ModelState.IsValid)
            {
                curs.Id = Guid.NewGuid().ToString();
                _context.Add(curs);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(curs);
        }

        // GET: Curs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curs = await _context.Curs.SingleOrDefaultAsync(m => m.Id == id);
            if (curs == null)
            {
                return NotFound();
            }
            return View(curs);
        }

        // POST: Curs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AcronimValuta,ActualizareValuta,CasierId,CursCumparare,CursOficialBnr,CursVanzare,DataCurs,DenumireValuta,Multiplu,NumarCurentValuta,NumarLista,ParitateEuro,PozitieValuta,SoldCurentValuta,TipValuta")] Curs curs)
        {
            if (id != curs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursExists(curs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(curs);
        }

        // GET: Curs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curs = await _context.Curs.SingleOrDefaultAsync(m => m.Id == id);
            if (curs == null)
            {
                return NotFound();
            }

            return View(curs);
        }

        // POST: Curs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var curs = await _context.Curs.SingleOrDefaultAsync(m => m.Id == id);
            _context.Curs.Remove(curs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CursExists(string id)
        {
            return _context.Curs.Any(e => e.Id == id);
        }
    }
}

SchimbValutar/UI.MVC/Controllers/TaraController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Domain_Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UI.MVC.Data;

namespace UI.MVC.Controllers
{
    public class TaraController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaraController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Tara
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tara.ToListAsync());
        }

        // GET: Tara/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tara = await _context.Tara.SingleOrDefaultAsync(m => m.Id == id);
            if (tara == null)
            {
                return NotFound();
            }

            return View(tara);
        }

        // GET: Tara/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tara/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cod,Denumire,TotalCumparariEuro,TotalVanzariEuro")] Tara tara)
        {
            if (ModelState.IsValid)
            {
                tara.Id = Guid.NewGuid().ToString();
                _context.Add(tara);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tara);
        }

        // GET: Tara/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tara = await _context.Tara.SingleOrDefaultAsync(m => m.Id == id);
            if (tara == null)
            {
                return NotFound();
            }
            return View(tara);
        }

        // POST: Tara/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Cod,Denumire,TotalCumparariEuro,TotalVanzariEuro")] Tara tara)
        {
            if (id != tara.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tara);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaraExists(tara.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(tara);
        }

        // GET: Tara/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tara = await _context.Tara.SingleOrDefaultAsync(m => m.Id == id);
            if (tara == null)
            {
                return NotFound();
            }

            return View(tara);
        }

        // POST: Tara/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var tara = await _context.Tara.SingleOrDefaultAsync(m => m.Id == id);
            _context.Tara.Remove(tara);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TaraExists(string id)
        {
            return _context.Tara.Any(e => e.Id == id);
        }
    }
}

SchimbValutar/UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchimbValutar</title>

    <environment names="Development">
        <script src="https://use.fontawesome.com/7a9684a1ae.js"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/images/logo.png" alt="Logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <!--<ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Owner">Admin</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Client">Manager</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Employee">Employee</a>
                    </li>
                </ul>-->
                @await Html.PartialAsync("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="fluid-container body-content">
        @RenderBody()
        <hr />
        <footer class="container">
            <p>&copy; 2016 - SchimbValutar</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>


@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schimb Valutar</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Schimb Valutar</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Card" asp-action="Index">Carduri</a></li>
                    <li><a asp-area="" asp-controller="Casier" asp-action="Index">Casieri</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="Index">Clienti</a></li>
                    <li><a asp-area="" asp-controller="Curs" asp-action="Index">Cursuri</a></li>
                    <li><a asp-area="" asp-controller="Operatie" asp-action="Index">Operatii</a></li>
                    <li><a asp-area="" asp-controller="Tara" asp-action="Index">Tari</a></li>
                    <li><a asp-area="" asp-controller="Valuta" asp-action="Index">Valute</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - UI.MVC</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>*@